### ISSUE TITLE
Automate Pump CSL Version

### ISSUE THREAD

**Issue by ljttl3q04t** [minswap/cardano-serialization-lib#31]
### Using Github CI to automatic pump CSL version whenever PR merged to `minswap-11`

**Comment by longngn** [comment]
How to:
1. Create a Github Actions job on new push to main
2. Find next version
3. Run `./scripts/pump-version.sh <new-version>`

How to test:
- Create your own Github org, fork this repo to your org, create your NPM account and publish to your NPM account
- Everything in public so those should be free
